tax_providers:
  softdreams:
    url: https://tracuu.easyinvoice.vn/
    status: RESOLVED
    note: Working properly
  dna:
    url: https://hoadondientu.gdt.gov.vn/tra-cuu
    status: TBD
    note: null
  misa:
    url: https://www.meinvoice.vn/tra-cuu/
    status: TBD
    note: null
  invoice:
    url: https://tracuuhoadon.minvoice.com.vn/
    status: TBD
    note: null
  viettel:
    url: https://sinvoice-viettel.vn/tra-cuu-hoa-don/
    status: TBD
    note: null
  bkav:
    url: https://tracuu.ehoadon.vn/
    status: TBD
    note: null
  wintech:
    url: https://tracuu.wininvoice.vn/
    status: TBD
    note: null
  thaison:
    url: https://einvoice.vn/tra-cuu
    status: TBD
    note: null
  buuchinhvt:
    url: https://portaltool-miennam.vnpt-invoice.com.vn/
    status: TBD
    note: null
  visnam:
    url: https://hddt.vin-hoadon.com/
    status: TBD
    note: null
  fpt:
    url: https://tracuuhoadon.fpt.com.vn/
    status: TBD
    note: null