tax_providers:
  softdreams:
    search_url: https://tracuu.easyinvoice.vn/
    status: RESOLVED
    note: null
  dna:
    search_url: https://hoadondientu.gdt.gov.vn/tra-cuu
    status: TBD
    note: null
  misa:
    search_url: https://www.meinvoice.vn/tra-cuu/
    status: RESOLVED
    note: Working properly
  invoice:
    search_url: https://tracuuhoadon.minvoice.com.vn/
    status: TBD
    note: null
  viettel:
    search_url: https://vinvoice.viettel.vn/utilities/invoice-search
    status: RESOLVED
    note: null
  bkav:
    search_url: https://tracuu.ehoadon.vn/
    status: BLOCKED
    note: There is no search code in the json file. Need to be extracted from the email.
  wintech:
    search_url: https://tracuu.wininvoice.vn/
    status: TBD
    note: null
  thaison:
    search_url: https://einvoice.vn/tra-cuu
    status: RESOLVED
    note: null
  buuchinhvt:
    search_url: https://portaltool-miennam.vnpt-invoice.com.vn/
    status: RESOLVED
    note: null
  visnam:
    search_url: https://hddt.vin-hoadon.com/
    status: TBD
    note: null
  vina:
    search_url: https://tracuuhd.smartsign.com.vn/
    status: RESOLVED
    note: null
  hilo:
    search_url: https://vn.einvoice.grab.com/
    status: RESOLVED
    note: null
  fpt:
    search_url: https://tracuuhoadon.fpt.com.vn/
    status: RESOLVED
    note: not able to find "search code" from xml. reference:https://ketoan247.vn/cach-tra-cuu-hoa-don-goc-cua-ben-ban-tu-file-xml-tren-trang-hoadondientu-gdt-gov-vn-cua-tong-cuc-thue/. Extract data from email and process via KIMTIN_list.txt
# seller_short_name:
#   CONGTYTNHHTHUONGMAIVANTAINGUYENPHUOC: 'NGUYENPHUOC',
#   CONGTYTNHHTHUONGMAIMAYVY: 'MAYVY',
#   CONGTYCPDUOCPHAMPHUCTHIEN: 'PHUCTHIEN',
#   CONGTYTNHHTHUONGMAIDICHVUTRANGTHIETBIYTEMINHTRI: 'MINHTRI',
#   CONGTYTNHHFULLERTONHEALTHVIETNAM: 'FULLERTONHEALTHVIETNAM',
#   CONGTYTNHHGRAB: 'GRAB',
#   CONGTYTNHHNEMVANTHANH: 'NEMVANTHANH',
#   CONGTYCOPHANMORINAGANUTRITIONALFOODSVIETNAM: 'MORINAGANUTRITIONALFOODSVIETNAM',
#   CongTyTNHHThuongMaiDauTuDinhVang: 'DinhVang',
#   CONGTYCOPHANTHUONGMAIDICHVUDOANKHOAHOC: 'DOANKHOAHOC',
#   CONGTYTRACHNHIEMHUUHANTHUONGMAIDICHVUTHIETBIYTENGUYENKHOA: 'NGUYENKHOA',
#   CONGTYTNHHTUVANVBP: 'VBP',
#   CONGTYTNHHTHIENANNAM: 'THIENANNAM',
#   CONGTYCOPHANTOPCVVIETNAM: 'TOPCVVIETNAM',
#   CONGTYTNHHDAUTUVAKINHDOANHBATDONGSANMYCANH: 'MYCANH',
#   CONGTYTNHHSANXUATTHUONGMAIVADICHVUALOBUYVIETNAM: 'ALOBUYVIETNAM',
#   CONGTYTNHHSAIGONBOULEVARDCOMPLEX: 'SAIGONBOULEVARDCOMPLEX',
#   CONGTYTNHHTHIETBIYTETHIENTRI: 'THIENTRI',
#   CONGTYTNHHMOTTHANHVIENNHATCHIMAI: 'NHATCHIMAI',
#   CONGTYTNHHKINGSMENVIETNAM: 'KINGSMENVIETNAM',
#   CONGTYCPDUOCLIEUTRUNGUONG2\(PHYTOPHARMA\\)': 'DUOCLIEUTRUNGUONG2',
#   CONGTYTNHHDKSHVIETNAM: 'DKSHVIETNAM',
#   CONGTYTNHHTHIETBIDUYMINH: 'DUYMINH',
#   CONGTYTNHHTRANGTHIETBIYTETRANVATRUNG: 'TRANVATRUNG',
#   CONGTYCOPHANNIPPONPAPERVIETHOAMY: 'NIPPONPAPERVIETHOAMY',
#   CONGTYTNHHTHUONGMAIVADICHVUCAFAM: 'CAFAM',
#   CONGTYCOPHANCONGNGHEC': 'CONGNGHEC',
#   CONGTYTNHHCOWAYVINA: 'COWAYVINA',
#   CONGTYTNHHSAIGONBOULEVARDCOMPLEX: 'SAIGONBOULEVARDCOMPLEX',
#   CONGTYCOPHANDAUTUTHIETBIYTETHIENAN: 'THIENAN',
#   CONGTYTNHHINSONGTHINH: 'SONGTHINH',
#   CONGTYTNHHSGSAGAWAVIETNAM: 'SGSAGAWAVIETNAM',
#   CONGTYCOPHANANHDUONGVIETNAM: 'ANHDUONGVIETNAM',
#   CONGTYTNHHTHIETBIYTENDENT: 'NDENT',
#   TrungtamKinhdoanhVNPTthanhphoHoChiMinhChinhanhTongcongtyDichvuVienthong': 'VNPT_HCM',
#   TRUNGTAMKINHDOANHVNPTHANOI-CHINHANHTONGCONGTYDICHVUVIENTHONG': 'VNPT_HaNoi',

profiles:
  vantoi:
    db: "data/vantoi/vantoi.db"
    hoadondientu:
      username: "0313823273"
      password: "Vantoi&kt05"
    KIMTIN_list_path: "data/vantoi/KIMTIN_list.txt"
    download_path: "data/vantoi/download"
    seller_short_name:
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ TPC": "TPC"
      "CÔNG TY TNHH KIM MINH C.L": "KIMMINHCL"
      "CÔNG TY TNHH MỘT THÀNH VIÊN THƯƠNG MẠI MINH TỚI": "MINHTOI"
      "CHI NHÁNH CÔNG TY CỔ PHẦN ĐÁ MÀI HẢI DƯƠNG (TỈNH HẢI DƯƠNG)": "HAIDUONG"
      "CÔNG TY CỔ PHẦN  QUE HÀN ĐIỆN VIỆT ĐỨC": "VIETDUC"
      "CÔNG TY CỔ PHẦN HÁN VINH": "HANVINH"
      "CÔNG TY TNHH TOÀN ĐẮC LỘC": "TOANDACLOC"
      "CÔNG TY TNHH THIẾT BỊ ĐIỆN THÀNH HIẾU": "THANHHIEU"
      "CÔNG TY TNHH  THIẾT BỊ HÀN VỮNG THỊNH": "VUNGTHINH"
      "CÔNG TY TNHH THƯƠNG MẠI - DỊCH VỤ - SẢN XUẤT KIẾN NGUYÊN": "KIENNGUYEN"
      "CÔNG TY TNHH DỊCH VỤ KẾ TOÁN THÚY ANH": "THUYANH"
      "CÔNG TY TNHH MỘT THÀNH VIÊN TM - XD SƠN HUYỀN S.Q.H": "SONHUYENSQH"
      "CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI CÔNG NGHIỆP SJL": "SJL"
      "CÔNG TY TNHH SẢN XUẤT - THƯƠNG MẠI DÂY VÀ CÁP ĐIỆN HIỆP THÀNH": "HIEPTHANH"
      "CÔNG TY TNHH TUẤN HÙNG MINH": "TUANHUNGMINH"
      "CÔNG TY TNHH XÂY DỰNG THÁI BÌNH MINH": "THAIBINHMINH"
      "CÔNG TY TNHH SẢN XUẤT QUE HÀN ĐẠI TÂY DƯƠNG VIỆT NAM": "DAITAYDUONGVIETNAM"
      "CÔNG TY TNHH THƯƠNG MẠI NHƠN HƯNG": "NHONHUNG"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ GIA MINH NGỌC": "GIAMINHNGOC"
      "CÔNG TY TNHH MTV DỊCH VỤ CÔNG ÍCH QUẬN 1": "CONGICHQUAN1"
      "CÔNG TY TNHH THƯƠNG MẠI - DỊCH VỤ VẢI NHÁM HỒ PHÁT": "HOPHAT"
      "CÔNG TY TNHH CUNG ỨNG THIẾT BỊ TOÀN TÂM": "TOANTAM"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VINH PHÚC": "VINHPHUC"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ THIẾT BỊ ĐIỆN SƠN HẢI": "SONHAI"
      "CÔNG TY CỔ PHẦN HẢI YẾN HÀ THÀNH": "HATHANH"
      "CÔNG TY TRÁCH NHIỆM HỮU HẠN GIA PHONG": "GIAPHONG"
      "CÔNG TY TNHH CƠ KHÍ HOÀNG PHẨM": "HOANGPHAM"
      "CÔNG TY TNHH GA RAN": "GARAN"
      "CÔNG TY CỔ PHẦN CÔNG NGHỆ VÀ THIẾT BỊ CÔNG NGHIỆP VÊ GA": "VEGA"
      "CÔNG TY CỔ PHẦN THƯƠNG MẠI - DỊCH VỤ PHONG VŨ": "PHONGVU"
      "CÔNG TY TNHH TƯ VẤN XÂY DỰNG VÀ THƯƠNG MẠI LONG MINH": "LONGMINH"
      "CÔNG TY TNHH XUẤT NHẬP KHẨU ÁNH VÂN": "ANHVAN"
      "CÔNG TY TNHH MỘT THÀNH VIÊN KIM PHÁT THIÊN HƯƠNG": "KIMPHATTHIENHUONG"
      "Công Ty TNHH Thiết Bị Điện Công Nghiệp Quân Phạm": "QUANPHAM"
      "CÔNG TY TNHH THƯƠNG MẠI NAM VIỆT Á": "NAMVIETA"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ KỸ THUẬT CAO HÙNG": "CAOHUNG"
      "CÔNG TY TNHH CUNG ỨNG THIẾT BỊ VẬT TƯ - PCCC - BHLD HÀO PHÁT": "HAOPHAT"
      "CÔNG TY TNHH BHLD THANH HIỆP": "THANHHIEP"
      "CÔNG TY TNHH THƯƠNG MẠI HOÀNG NAM": "HOANGNAM"
      "CÔNG TY TNHH MTV M&M VIỆT NAM": "MMVIETNAM"
      "CÔNG TY TNHH THƯƠNG MẠI SEOUL – HÀ NỘI": "SEOULHANOI"
      "CÔNG TY TNHH HÀN CẮT VIỆT THỊNH": "VIETTHINH"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ HARO VIỆT NAM": "HAROVIETNAM"
      "CÔNG TY TNHH CÔNG NGHIỆP GK SÀI GÒN": "GKSAIGON"
      "CÔNG TY TNHH THƯƠNG MẠI KỸ THUẬT CƠ ĐIỆN CHÍ ANH": "CHIANH"
      "CÔNG TY TNHH THƯƠNG MẠI KIẾN THỊNH": "KIENTHINH"
      "CÔNG TY TNHH THƯƠNG MẠI XÂY DỰNG MINH HUY PHÁT": "MINHHUYPHAT" 
      "CHI NHÁNH CÔNG TY TRÁCH NHIỆM HỮU HẠN MAKITA VIỆT NAM TẠI THÀNH PHỐ HỒ CHÍ MINH": "MAKITAHCM"
      "CÔNG TY TNHH THU PHÍ TỰ ĐỘNG VETC": "VETC"
      "Ngân hàng TMCP Ngoại thương Việt Nam": "VIETCOMBANK"
      "Ngân hàng TMCP Sài Gòn Thương Tín - Chi nhánh Sài Gòn": "SACOMBANK"
      "CÔNG TY CỔ PHẦN TẬP ĐOÀN KIM TÍN": "KIMTIN"
      "Ngân hàng TMCP Ngoại thương Việt Nam - Chi nhánh TP. Hồ Chí Minh": "VIETCOMBANKHCM"
      "CHI NHÁNH TỔNG CÔNG TY CHUYỂN PHÁT NHANH BƯU ĐIỆN - CÔNG TY CỔ PHẦN TẠI THÀNH PHỐ HỒ CHÍ MINH": "CHUYENPHATNHANHHCM"
      "NGÂN HÀNG TNHH MTV SHINHAN VIỆT NAM - CHI NHÁNH ĐÔNG SÀI GÒN": "SHINHANBANKDONGSAIGON"
      "CÔNG TY TNHH SẢN XUẤT - THƯƠNG MẠI TÍN HƯNG": "TINHUNG"
      "CÔNG TY TNHH RILAND VIỆT  NAM": "RILANDVIETNAM"
      "CHI NHÁNH CÔNG TY CỔ PHẦN PIZZA 4PS - NHÀ HÀNG PIZZA 4PS COBI TOWER": "PIZZA4PS"
      "CÔNG TY CỔ PHẦN SẢN XUẤT VÀ THƯƠNG MẠI HÒA THỊNH": "HOATHINH"
      "CÔNG TY TNHH CƠ KHÍ THƯƠNG MẠI THÁI MINH": "THAIMINH"
      "CÔNG TY TNHH THƯƠNG MẠI - DỊCH VỤ VĨNH PHONG": "VINHPHONG"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ TOPWIN": "TOPWIN"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ DELI AN": "DELIAN"
      "CÔNG TY TRÁCH NHIỆM HỮU HẠN LỄ NGHI": "LENGHI"
      "CÔNG TY TNHH NGUYỄN HOÀNG HUYNH": "NGUYENHOANGHUYNH"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ DT MART": "DTMART"
      "CÔNG TY TNHH THƯƠNG MẠI PHƯỚC NHẬT": "PHUOCNHAT"
      "CÔNG TY TRÁCH NHIỆM HỮU HẠN GIA PHÚC ÂN": "GIAPHUCAN"
      "CÔNG TY TNHH MINH HÙNG TOOL": "MINHHUNGTOOL"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ HOÀNG HUY NAM": "HOANGHUYNAM"
      "CÔNG TY TNHH THIÊN PHÚ KIM": "THIENPHUKIM"
      "CÔNG TY CỔ PHẦN ĐIỆN TỬ VIỄN THÔNG ÁNH DƯƠNG": "DTVTANHDUONG"
      "CÔNG TY TNHH HỒNG PHÚC LEGENDS": "HONGPHUCLEGENDS"
      "CÔNG TY CỔ PHẦN NHIÊN LIỆU SÀI GÒN": "SAIGONPETRO"
      "CÔNG TY CỔ PHẦN XĂNG DẦU DẦU KHÍ VŨNG TÀU": "DAUKHIVUNGTAU"
      "CÔNG TY TNHH MỘT THÀNH VIÊN DẦU KHÍ THÀNH PHỐ HỒ CHÍ MINH": "DAUKHITPHCM"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ & SẢN XUẤT VIỆT Á": "VIETA"
      "CÔNG TY CỔ PHẦN ĐÁ MÀI SỐ 1 HẢI DƯƠNG": "DAMAISO1HAIDUONG"
      "CÔNG TY TNHH ĐIỆN CƠ HASAKI VIỆT NAM": "HASAKIVIETNAM"
      "CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI DỊCH VỤ ĐẠI THƯƠNG TÍN": "DAITHUONGTIN"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ THIẾT BỊ ÁNH DƯƠNG": "THIETBIANHDUONG"
      "CÔNG TY TNHH THƯƠNG MẠI VIỄN THÔNG THANH HÀ": "THANHHA"
      "CÔNG TY CỔ PHẦN DIỆP TẤN PHÁT": "DIEPTANPHAT"
      "CÔNG TY TNHH TM LIÊN PHÁT KHOA VIỆT NAM": "LIENPHATKHOAVIETNAM"
      "CÔNG TY TNHH THƯƠNG MẠI CƠ KHÍ TÙNG NGŨ KIM": "TUNGNGUKIM"
    # TODO: load start_date and end_date from config
    # start_date: "01/02/2025"
    # end_date: "30/04/2025"
  dym_q1:
    db: "data/dym_q1/dym_q1.db"
    hoadondientu:
      username: "0316060982"
      password: "1Q68nmL$"
    download_path: "data/dym_q1/download"
    seller_short_name:
      "CÔNG TY TNHH THƯƠNG MẠI VẬN TẢI NGUYỄN PHƯỚC": "NGUYENPHUOC"
      "CÔNG TY TNHH THƯƠNG MẠI MAY VY": "MAYVY"
      "VIỆN PASTEUR TP.HCM": "PASTEURTPHCM"
      "CÔNG TY CP DƯỢC PHẨM PHÚC THIỆN": "PHUCTHIEN"
      "CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ TRANG THIẾT BỊ Y TẾ MINH TRÍ": "MINHTRI"
      "CÔNG TY TNHH FULLERTON HEALTH VIỆT NAM": "FULLERTONHEALTHVIETNAM"
      "CÔNG TY TNHH GRAB": "GRAB"
      "CÔNG TY CỔ PHẦN MORINAGA NUTRITIONAL FOODS VIỆT NAM": "MORINAGANUTRITIONALFOODSVIETNAM"
      "Công Ty TNHH Thương Mại Đầu Tư Đỉnh Vàng": "DINHVANG"
      "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ ĐOÀN KHOA HỌC": "DOANKHOAHOC"
      "CÔNG TY TRÁCH NHIỆM HỮU HẠN THƯƠNG MẠI DỊCH VỤ THIẾT BỊ Y TẾ NGUYÊN KHOA": "NGUYENKHOA"
      "CÔNG TY TNHH TƯ VẤN VBP": "VBP"
      "CÔNG TY TNHH NỆM VẠN THÀNH": "NEMVANTHANH"
      "CÔNG TY TNHH THIÊN AN NAM": "THIENANNAM"
      "CÔNG TY CỔ PHẦN TOPCV VIỆT NAM": "TOPCVVIETNAM"
      "CÔNG TY TNHH ĐẦU TƯ VÀ KINH DOANH BẤT ĐỘNG SẢN MỸ CẢNH": "MYCANH"
      "CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI VÀ DỊCH VỤ ALOBUY VIỆT NAM": "ALOBUYVIETNAM"
      "CÔNG TY TNHH SÀI GÒN BOULEVARD COMPLEX": "SAIGONBOULEVARDCOMPLEX"
      "CÔNG TY TNHH THIẾT BỊ Y TẾ THIỆN TRÍ": "THIENTRI"
      "CÔNG TY TNHH MỘT THÀNH VIÊN NHẤT CHI MAI": "NHATCHIMAI"
      "CÔNG TY TNHH KINGSMEN VIỆT NAM": "KINGSMENVIETNAM"
      "CÔNG TY TNHH THIẾT BỊ DUY MINH": "DUYMINH"
      "CÔNG TY TNHH TRANG THIẾT BỊ Y TẾ TRẦN VÀ TRUNG": "TRANVATRUNG"
      "CÔNG TY CỔ PHẦN NIPPON PAPER VIỆT HOA MỸ": "NIPPONPAPERVIETHOAMY"
      "CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ CAFAM": "CAFAM"
      "CÔNG TY CỔ PHẦN CÔNG NGHỆ C+": "CONGNGHEC"
      "CÔNG TY TNHH COWAY VINA": "COWAYVINA"
      "CÔNG TY CỔ PHẦN MEDCOMTECH": 
      "CÔNG TY CỔ PHẦN ĐẦU TƯ THIẾT BỊ Y TẾ THIÊN ÂN": "THIENAN"
      "CÔNG TY TNHH IN SONG THỊNH": "SONGTHINH"
      "CÔNG TY TNHH SG SAGAWA VIỆT NAM": "SGSAGAWAVIETNAM"
      "CÔNG TY TNHH THIẾT BỊ Y TẾ NDENT": "NDENT"
      "CÔNG TY CP DƯỢC LIỆU TRUNG ƯƠNG 2 (PHYTOPHARMA)": "DUOCLIEUTRUNGUONG2"
      "CÔNG TY TNHH DKSH VIỆT NAM": "DKSHVIETNAM"
      "CÔNG TY CỔ PHẦN ÁNH DƯƠNG VIỆT NAM": "ANHDUONGVIETNAM"
      "Trung tâm Kinh doanh VNPT thành phố Hồ Chí Minh - Chi nhánh Tổng công ty Dịch vụ Viễn thông": "VNPT_HCM"
      "TRUNG TÂM KINH DOANH VNPT - HÀ NỘI - CHI NHÁNH TỔNG CÔNG TY DỊCH VỤ VIỄN THÔNG": "VNPT_HaNoi"
    # TODO: load start_date and end_date from config
    # start_date: "01/05/2025"
    # end_date: "12/05/2025"

# in-used-profile: "dym_q1"
in-used-profile: "vantoi"