tax_providers:
  softdreams:
    search_url: https://tracuu.easyinvoice.vn/
    status: TBD
    note: null
  dna:
    search_url: https://hoadondientu.gdt.gov.vn/tra-cuu
    status: TBD
    note: null
  misa:
    search_url: https://www.meinvoice.vn/tra-cuu/
    status: RESOLVED
    note: Working properly
  invoice:
    search_url: https://tracuuhoadon.minvoice.com.vn/
    status: TBD
    note: null
  viettel:
    search_url: https://vinvoice.viettel.vn/utilities/invoice-search
    status: TBD
    note: null
  bkav:
    search_url: https://tracuu.ehoadon.vn/
    status: TBD
    note: null
  wintech:
    search_url: https://tracuu.wininvoice.vn/
    status: TBD
    note: null
  thaison:
    search_url: https://einvoice.vn/tra-cuu
    status: TBD
    note: null
  buuchinhvt:
    search_url: https://portaltool-miennam.vnpt-invoice.com.vn/
    status: TBD
    note: null
  visnam:
    search_url: https://hddt.vin-hoadon.com/
    status: TBD
    note: null
  fpt:
    search_url: https://tracuuhoadon.fpt.com.vn/
    status: BLOCKED
    note: not able to find "search code" from xml. reference:https://ketoan247.vn/cach-tra-cuu-hoa-don-goc-cua-ben-ban-tu-file-xml-tren-trang-hoadondientu-gdt-gov-vn-cua-tong-cuc-thue/